name: delete-old-packages
on:
  workflow_dispatch:

jobs:
  delete-old-packages:
    runs-on: ubuntu-latest
      
    steps:
      - name: Delete package
        uses: OmarCastro/delete-package-versions@d2531724efdbb55705ba2050c9460c2e87127a0f
        with: 
            owner: OmarCastro
            repo: github-actions-test-3
            package-names: actions-test, github-actions-*
            min-versions-to-keep: 2
            token: ${{ secrets.PAT }}

 


          
